In [1]:
import numpy as np

In [13]:
s=10000
matrices=[]
for i in range(1,100,2):
    matrix=np.zeros((s,s),dtype="bool")
    x=i/100
    for j in range(s):
        for k in range(j,s):
            p=np.random.rand()
            if x>p:
                matrix[j,k]=1
                matrix[k,j]=1
    matrices.append(matrix)


In [20]:
matrices=np.array(matrices)

In [21]:
matrices

array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, Fal

In [22]:
edges=[]
for i in matrices:
    edges.append(np.sum(i))

In [24]:
edges=np.array(edges)

In [25]:
edges

array([ 1000459,  3000614,  4996609,  7005094,  9001130, 11001117,
       12997841, 15000460, 16991861, 19007024, 20991219, 22995109,
       25003817, 26996227, 29004777, 30997451, 32992454, 35002315,
       36987587, 38998921, 40992700, 42990112, 45005948, 46995723,
       49013889, 50996571, 52991518, 55002599, 56990332, 58992661,
       61001446, 63001388, 64998392, 67005875, 68997004, 70987518,
       72992811, 75004074, 76998914, 79006134, 81006423, 82994683,
       84998130, 86997175, 88999859, 91000173, 93003403, 95004733,
       97000404, 98998667])

In [26]:
degrees=[]
for i in matrices:
    degrees.append(np.sum(i,1))

In [30]:
degrees=np.array(degrees)

In [31]:
degrees

array([[ 111,  100,  119, ...,  118,   90,   96],
       [ 308,  306,  287, ...,  300,  296,  285],
       [ 514,  512,  562, ...,  502,  488,  489],
       ...,
       [9502, 9488, 9522, ..., 9509, 9517, 9531],
       [9701, 9697, 9689, ..., 9711, 9747, 9684],
       [9902, 9908, 9914, ..., 9895, 9905, 9902]])